# see: https://python-poetry.org/docs/pyproject/

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "sedaro"
version = "0.1.0"
description = "A python client to interact with the Sedaro Satellite API."
license = "MIT" # FIXME
authors = [
  "Sedaro <support@sedarotech.com>",
]
maintainers = [
    "Sedaro <support@sedarotech.com>",
]
readme = "README.md"
homepage = "https://www.sedaro.com/" # FIXME : An URL to the website of the project
repository = "https://gitlab.sedaro.com/sedaro-satellite/clients" #FIXME
# documentation = "..." # FIXME
keywords = ["simuilation", "sedaro", "digital twin"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # FIXME
    "Operating System :: OS Independent", # FIXME
    "Topic :: Software Development",
]
packages = [
    { include = "src/sedaro" },
]

[tool.poetry.dependencies]
python = "^3.9"
pydash = "^5.1.1"

typing-extensions = "^4.3.0"
# added ^^^ typing-extensions b/c generated python_client tries to "import from typing_extensions" (convention in
# older version of python), and should now be an "import from typing". This is a workaround.

# sedaro_base_client = { path = "src/sedaro_base_client/", develop = false }
# sedaro_base_client = { path = "src/sedaro_base_client/dist/sedaro_base_client-1.0.0.tar.gz", develop = false }
# couldn't get this to work (either way) 
# based on: https://python-poetry.org/docs/dependency-specification#path-dependencies
# I believe this is the bug: https://github.com/python-poetry/poetry/issues/5273#issuecomment-1274957953